<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Calculate_Price_TestSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>ad969b13-1b7e-45af-9313-3182eefd2c25</testSuiteGuid>
   <testCaseLink>
      <guid>32e249e3-46ad-492a-8a52-48adee5261d1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Hitung_Harga_Properti_POS</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>32271ae5-2bcf-46e8-991f-cdf59fe0871b</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>1-5</value>
         </iterationEntity>
         <testDataId>Data Files/TD_Hitung_Harga_Properti</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>32271ae5-2bcf-46e8-991f-cdf59fe0871b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Income</value>
         <variableId>d2df86ac-fc6b-4225-98ed-e2a5d638ed30</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>32271ae5-2bcf-46e8-991f-cdf59fe0871b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Expense</value>
         <variableId>cffb5819-fd19-46ab-8faa-1ef8101aac30</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>32271ae5-2bcf-46e8-991f-cdf59fe0871b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Years</value>
         <variableId>41a6ca04-f9b5-4783-b54e-bcb683d12d84</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>973e8f19-4cd0-46ac-bba7-93698f449e51</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Hitung_Harga_Properti_NEG</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>4258a9b9-5678-4ff4-8c97-bb73ed424c8e</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>6-7</value>
         </iterationEntity>
         <testDataId>Data Files/TD_Hitung_Harga_Properti</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>4258a9b9-5678-4ff4-8c97-bb73ed424c8e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Income</value>
         <variableId>4db6a1c7-c770-4bd1-bf27-8d7606260fef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>4258a9b9-5678-4ff4-8c97-bb73ed424c8e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Expense</value>
         <variableId>6da01ee5-2d83-4ad6-9a8d-971b5e2dff67</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>4258a9b9-5678-4ff4-8c97-bb73ed424c8e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Years</value>
         <variableId>c8e3d4f8-50b8-47cd-90ad-11b2bf48237d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
