<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Hitung</name>
   <tag></tag>
   <elementGuidId>a544cf6b-bab5-4bd7-86e9-61d268b0a9af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-main.px-5.d-block.w-100</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9ff5da5f-e38e-4f5e-b3bb-e3e7c673eca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>bfe9e54c-294a-400a-b36d-e4068c26f857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-main px-5 d-block w-100</value>
      <webElementGuid>f007d240-3a55-4a52-a7c8-3f3c39af9be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hitung</value>
      <webElementGuid>4a1625fa-1ad1-40e0-a668-6cc3bd9ea644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hitung_harga_button&quot;)/button[@class=&quot;btn btn-main px-5 d-block w-100&quot;]</value>
      <webElementGuid>d7223b74-b2da-4203-acc6-5212000c9898</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[4]</value>
      <webElementGuid>ba25fcbc-a54d-4f26-b651-e439684292e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hitung_harga_button']/button</value>
      <webElementGuid>7b05278b-504b-4d14-84c2-60f4e79fd1de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jangka Waktu'])[2]/following::button[1]</value>
      <webElementGuid>cab97333-d55c-46f0-ba20-fb1fd4ef79f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Per Bulan'])[2]/following::button[1]</value>
      <webElementGuid>bc73ae06-9ca5-42da-9599-195c2fddd58d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CARI PROPERTI'])[1]/preceding::button[1]</value>
      <webElementGuid>aa463cfb-4de7-4822-b6e9-832de300002b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rumah'])[1]/preceding::button[1]</value>
      <webElementGuid>1165f390-9924-4523-91db-597bf79b6664</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hitung']/parent::*</value>
      <webElementGuid>037c3f98-3f1d-49c4-a4c1-8587fe0a9598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/button</value>
      <webElementGuid>f5478a15-2eca-44c9-919f-8c44230e161d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Hitung' or . = 'Hitung')]</value>
      <webElementGuid>f0fe4458-cc37-48d5-b6be-2026fd1eec43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
